version: '3'

tasks:
  pre-commit:
    desc: Run pre-commit hooks
    cmds:
      - pre-commit run --show-diff-on-failure --color=always

  pre-commit-all:
    desc: Run pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files
